from tkinter import *
window=Tk()
window.geometry('300x320')
window.configure(bg='yellow')
window.title('UJJWAL CREATION')
# CREATE A LABEL
label=Label(window,text="""S.B.MILLS SER.
SECONDARY SCHOOL""",fg='black',bg='white',relief='solid')
label.grid(row=0,column=1)
label1=Label(window,text='REGISTRATION FORM',fg='white',bg='black',relief='solid')
label1.grid(row=1,column=1)
label2=Label(window,text='-----NAME-----',fg='white',bg='black',relief='solid')
label2.grid(row=2,column=0)
label3=Label(window,text='------AGE-------',fg='black',bg='white',relief='solid')
label3.grid(row=3,column=0)
label4=Label(window,text='----CLASS-----',fg='white',bg='black',relief='solid')
label4.grid(row=4,column=0)
labelO=Label(window,text='-------DOB------',fg='black',bg='white',relief='solid')
labelO.grid(row=5,column=0)
label5=Label(window,text='---ADDRESS---',fg='white',bg='black',relief='solid')
label5.grid(row=6,column=0)
label6=Label(window,text='-MOBILE NO.-',fg='black',bg='white',relief='solid')
label6.grid(row=7,column=0)
label7=Label(window,text='----EMAIL ID---',fg='white',bg='black',relief='solid')
label7.grid(row=8,column=0)
# CREATE A ENTRY BOX
entry=Entry(window,fg="black",bg="white",relief="solid")
entry.grid(row=2,column=1)
entry1=Entry(window,fg="white",bg="black",relief="solid")
entry1.grid(row=3,column=1)
entry2=Entry(window,fg="black",bg="white",relief="solid")
entry2.grid(row=4,column=1)
entry3=Entry(window,fg="white",bg="black",relief="solid")
entry3.grid(row=5,column=1)
entry4=Entry(window,fg="black",bg="white",relief="solid")
entry4.grid(row=6,column=1)
entry5=Entry(window,fg="white",bg="black",relief="solid")
entry5.grid(row=7,column=1)
entry6=Entry(window,fg="black",bg="white",relief="solid")
entry6.grid(row=8,column=1)
# CREATE A BUTTON
btn=Button(window,text="SUBMIT IT")
btn.grid(row=9,column=1)

btn1=Button(window,text="EXIT",command=window.destroy)
btn1.grid(row=10,column=1)

labell=Label(window,text="""PROGRAM DESIGNED BY 
UJJWAL SAINI ●_●""",fg="white",bg="black",relief="solid")
labell.grid(row=11,column=1)
window.mainloop()
print("GOODBYE")
print("DESIGNED BY UJJWAL SAINI")
